services:
  - type: web
    name: suart-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8001
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health

  - type: web
    name: suart-frontend
    env: static
    buildCommand: cd react-interface && npm install && npm run build
    staticPublishPath: ./react-interface/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
